LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := zygisk_ff_belajar
LOCAL_SRC_FILES := main.cpp

LOCAL_LDLIBS := -llog -landroid

# WAJIB MENGGUNAKAN CPPFLAGS DAN C++20 UNTUK MENGHILANGKAN ERROR MAKRO ZYGISK
LOCAL_CPPFLAGS := -std=c++20
LOCAL_CFLAGS := -Wall -O3

include $(BUILD_SHARED_LIBRARY)
