name: Build Zygisk Module

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil semua file kodingan dari repository GitHub kamu
      - name: Ambil Kode Proyek
        uses: actions/checkout@v4

      # 2. Memasang alat masak Android NDK versi r25c di server GitHub
      - name: Siapkan Android NDK r25c
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: true

      # 3. Mengeksekusi instruksi dari file Android.mk dan Application.mk kamu
      - name: Mulai Kompilasi Kode (ndk-build)
        run: |
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

      # 4. Menyusun struktur file dan mengompresnya menjadi ZIP otomatis
      - name: Proses dan Kemas Jadi ZIP Modul Magisk
        run: |
          # Memindahkan file biner arm64-v8a.so ke halaman depan (root)
          cp libs/arm64-v8a/arm64-v8a.so ./
          
          # Membuat folder penampung sementara untuk zip agar bersih
          mkdir -p keluar_modul
          
          # Membungkus file-file wajib secara sejajar ke dalam file zip
          zip -r keluar_modul/Zygisk_ESP_FF_Belajar.zip arm64-v8a.so customize.sh module.prop

      # 5. Mengunggah file ZIP instan yang siap download dan siap flash
      - name: Unggah File ZIP Siap Flash
        uses: actions/upload-artifact@v4
        with:
          name: Modul-Zygisk-Siap-Flash
          path: keluar_modul/Zygisk_ESP_FF_Belajar.zip
